python -m imet.main train resnet_320_bce_1 \
--model resnet50 \
--n-epochs 1000 \
--batch-size 16 \
--lr 0.001 \
--size 320 \
--loss BCE \
--train_augments "random_crop, horizontal_flip, vertical_flip, random_rotate, color_jitter" \
--test_augments "random_crop, horizontal_flip, vertical_flip" \
--augment_ratio 0.5 \
--scheduler cosine \
--worker 8 \
--fold 1
